# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame_3 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalFrame_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_26 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 6, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 2, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 8, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 7, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 1, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 7, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 8, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 7, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 5, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 4, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 8, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_55 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_3.addWidget(self.label_55)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.verticalFrame_3)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalFrame_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalFrame_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(0)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalFrame_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalFrame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalFrame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalFrame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.verticalFrame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Компоненты"))
        self.label_2.setText(_translate("MainWindow", "Max.%"))
        self.label_26.setText(_translate("MainWindow", "0"))
        self.label_46.setText(_translate("MainWindow", "Метионин"))
        self.label_17.setText(_translate("MainWindow", "Кальций"))
        self.label_37.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "КДж"))
        self.label_23.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Фосфор"))
        self.label_47.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Сырой протеин"))
        self.label_31.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Сырой клетчатки"))
        self.label_25.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Натрий"))
        self.label_36.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "Лизин"))
        self.label_20.setText(_translate("MainWindow", "0"))
        self.label_35.setText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Питательность"))
        self.label_14.setText(_translate("MainWindow", "Получена"))
        self.label_11.setText(_translate("MainWindow", "Норма"))
        self.label_4.setText(_translate("MainWindow", "Нехватка"))
        self.label_55.setText(_translate("MainWindow", "Выберете тип птицы"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox.setItemText(1, _translate("MainWindow", "---Утки---"))
        self.comboBox.setItemText(2, _translate("MainWindow", "X11 крос"))
        self.comboBox.setItemText(3, _translate("MainWindow", "1-7д."))
        self.comboBox.setItemText(4, _translate("MainWindow", "---Куры---"))
        self.comboBox.setItemText(5, _translate("MainWindow", "22-47н."))
        self.comboBox.setItemText(6, _translate("MainWindow", "48>н."))
        self.comboBox.setItemText(7, _translate("MainWindow", "---Перепела---"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Перепела"))
        self.pushButton_5.setText(_translate("MainWindow", "+ "))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Сумма:</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "0%"))
        self.pushButton.setText(_translate("MainWindow", "Расчитать"))
        self.pushButton_4.setText(_translate("MainWindow", "Выход"))
        self.pushButton_3.setText(_translate("MainWindow", "Открыть базу"))
        self.pushButton_2.setText(_translate("MainWindow", "Сохранить"))

